export default [
  'Vodka',
  'Gin',
  'Rum',
  'Tequila',
  'Whiskey',
  'Bourbon',
  'Brandy',
  'Cognac',
  'Champagne',
  'Prosecco',
  'Red Wine',
  'White Wine',
  'Rosé Wine',
  'Campari',
  'Aperol',
  'Vermouth',
  'Triple Sec',
  'Cointreau',
  'Grand Marnier',
  'Blue Curaçao',
  'Peach Schnapps',
  'Midori',
  'Baileys Irish Cream',
  'Kahlúa',
  'Frangelico',
  'Amaretto',
  'Chambord',
  'Galliano',
  'Chartreuse',
  'Benedictine',
  'Angostura Bitters',
  'Peychaud’s Bitters',
  'Orange Bitters',
  'Grenadine',
  'Simple Syrup',
  'Honey Syrup',
  'Agave Syrup',
  'Lime Juice',
  'Lemon Juice',
  'Orange Juice',
  'Cranberry Juice',
  'Pineapple Juice',
  'Grapefruit Juice',
  'Coconut Cream',
  'Heavy Cream',
  'Egg White',
  'Mint Leaves',
  'Basil Leaves',
  'Rosemary Sprig',
  'Cucumber',
  'Ginger',
  'Jalapeño',
]
