export default [
  'Amaretto Sour',
  'Apple Pie',
  'Aviation',
  'Blackberry Margarita',
  'Boulevardier',
  'Cosmopolitan',
  'Cosmopolitan (Low-Cal)',
  'Espresso Martini',
  'Gimlet',
  'Gin Martini',
  'Ginger Peach Iced Tea',
  'Hemingway Daiquiri',
  'Holiday Spiced Old Fashioned',
  'Jalapeño Lime Shrub',
  'Kamikaze',
  'Lemon Drop',
  'Long Island Iced Tea',
  'Low-Cal Cosmopolitan',
  'Low-Cal Margarita',
  'Low-Cal Whiskey Sour',
  'Mai Tai',
  'Mango Margarita',
  'Manhattan',
  'Margarita',
  'Margarita - Mango',
  'Margarita - Mistletoe',
  'Margarita - Spicy',
  'Margarita (Low-Cal)',
  'Matcha Martini',
  'Mint Julep',
  'Mistletoe Margarita',
  'Negroni',
  'Northside',
  'Old Fashioned',
  'Old-Fashioned',
  'Old-Fashioned - Holiday Spiced',
  'Paper Plane',
  'Passion Fruit Margarita',
  'Rhubarb Spice Shrub',
  'Rum Breeze',
  'Rum Runner',
  'Sazerac',
  'Screwdriver',
  'Sex on the Beach',
  'Shrub - Jalapeño Lime',
  'Shrub - Rhubarb Spice',
  'Spiced Coffee',
  'Spicy Margarita',
  'Uptown Rocks',
  'Whiskey Smash',
  'Whiskey Sour',
  'Whiskey Sour  (Low-Cal)',
  "Witch's Heart",
]
