export default [
  { name: 'oz', isConvertable: true },
  { name: 'ml', isConvertable: true },
  { name: 'dash', isConvertable: false },
  { name: 'drop', isConvertable: false },
  { name: 'tsp', isConvertable: false },
  { name: 'tbsp', isConvertable: false },
  { name: 'cup', isConvertable: true },
  { name: 'pint', isConvertable: true },
  { name: 'shot', isConvertable: false },
  { name: 'grams', isConvertable: true },
  { name: 'twist', isConvertable: false },
  { name: 'wheel', isConvertable: false },
  { name: 'wedge', isConvertable: false },
  { name: 'pinch', isConvertable: false },
  { name: 'rim', isConvertable: false },
] as any
